export const USER_STEP_AUTH_VK = 'USER_STEP_AUTH_VK';
export const USER_STEP_AUTH_FB = 'USER_STEP_AUTH_FB';
export const USER_STEP_INPUTPASS = 'USER_STEP_INPUTPASS';
export const USER_TRAINING_TRACK = 'USER_TRAINING_TRACK';
